### ISSUE TITLE
مستندات s3 nodejs صحیح نیستند

### ISSUE THREAD

**Issue by babakdevgeek** [liara-cloud/docs#498]
سلام و درود خدمت شما اولن متشرکم دوما خواهشمندم مستندات ذکر شده رو تصحیح بفرمایید الان دو هفته هست من درگیرم و هنوز موفق نشدم از فایلای دانلودی رو باکت لینک دانلود بگیزم اونچه شما در داکومنتتون گفتید client.getSignedUrl همچین فاکنشنی تعریف نشده روی ابجکت ساخته شده از  S3Client . مجبور شدم از یک پکیج دیگه به اسم @aws-sdk/s3-request-presigner استفاده کنم که اینم فقط روی دولاپمنت جواب میده رو پروداکشن هرکاری کردم لینک دانلود درست درنیومد حتی قسمت هاست url برای خود امازون بود من با storage.iran.liara.space جابه جا کردم توی url ها ولی از هم url درست گیرم نیومد من واقعا لنگ این قضیه هستم منتظرم این ایراد برطرف بشه خودم هرچی گشتم راه حلی پیدا نکردم تا الان

**Comment by eyeamnoob** [comment]
سلام، وقتتون بخیر.
از اینکه در بهبود مستندات به ما کمک می‌کنید، از شما ممنونیم.
برای دریافت لینک دانلود object از bucket می‌تونید از قطعه کد زیر استفاده کنید:
```js
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");
require("dotenv").config();

const filename = "arch_nz.png";

const client = new S3Client({
  region: "default",
  endpoint: process.env.LIARA_ENDPOINT,
  credentials: {
    accessKeyId: process.env.LIARA_ACCESS_KEY,
    secretAccessKey: process.env.LIARA_SECRET_KEY,
  },
});
const params = {
  Bucket: process.env.LIARA_BUCKET_NAME,
  Key: filename,
};

const command = new GetObjectCommand(params);
getSignedUrl(client, command).then((url) => console.log(url));
```

توجه داشته باشید که متغیر `filename` رو به نام فایل موردنظر تغییر بدید و همچنین یک فایل `.env` همراه با متغیر‌های زیر بسازید:
```
LIARA_ACCESS_KEY=
LIARA_SECRET_KEY=
LIARA_ENDPOINT=
LIARA_BUCKET_NAME=
```
