### ISSUE TITLE
django files doc

### ISSUE THREAD

**Issue by amirreza8002** [liara-cloud/docs#507]
دو پیشنهاد بهبود:
```
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
```
این کد باید جایگزین کد بعدی که در مستندات اومده بشه:
`DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'`
 
به این استناد:
https://docs.djangoproject.com/en/5.0/ref/settings/#storages
https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-DEFAULT_FILE_STORAGE

--------------------------------------
```
INSTALLED_APPS = [
    "storages",
    ]
```
این کد نیازی نیست و میتونه حذف بشه

https://django-storages.readthedocs.io/en/latest/

-----------------------------------------

**Comment by A-Najmabadi** [comment]
سلام امیررضا عزیز 
مرسی بابت اینکه در بهبود هرچه بیشتر مستندات لیارا، به ما کمک می‌کنید. 
تغییرات در مستندات اعمال شد؛ منتظر دیگر پیشنهادات شما هستیم. خدا قوت!
