### ISSUE TITLE
Potential Redirect Loop in Nginx Configuration

### ISSUE THREAD

**Issue by vashian** [liara-cloud/docs#524]
Here’s the issue causing the problem with crawling the data, which results in the "too many redirects" error:

```nginx
location ~ ^/email-server/how-tos/connect-via-platform/go/?$ {
  return 301 /email-server/how-tos/connect-via-platform/go/;
}
```

Do we need this location block? It seems to create a redirect loop. I think we can remove it.

**Comment by A-Najmabadi** [comment]
Yes, we can remove it, this block is not needed and I guess it must be this: 

```nginx
location ~ ^/email-server/how-tos/connect-via-platform/golang/?$ {
  return 301 /email-server/how-tos/connect-via-platform/go/;
}
```

I'll fix this, thanks for your help!
